### ISSUE TITLE
In is.na(le) : is.na() applied to non-(list or vector) of type 'NULL'

### ISSUE THREAD

**Issue by fengfengyuyu** [rossb34/PortfolioAnalyticsPresentation#1]
Hi,
- i run below codes ( your presentation demo in rinfinance 2014):

suppressMessages(library(ROI.plugin.quadprog))
suppressMessages(library(ROI.plugin.glpk))
suppressMessages(library(ROI.plugin.quadprog))
suppressMessages(library(ROI))
suppressMessages(library(iterators))
suppressMessages(library(foreach))
suppressMessages(library(PortfolioAnalytics))

R <- edhec[,c("Convertible.Arbitrage", "Equity.Market.Neutral", 
 "Fixed.Income.Arbitrage", 
 "CTA.Global", "Emerging.Markets", "Global.Macro")]
colnames(R) <- c("CA", "EMN", "FIA", "CTAG", "EM", "GM")

funds <- colnames(R)
portf.init <- portfolio.spec(funds)
portf.init <- add.constraint(portf.init, type="weight_sum", 
 min_sum=0.99, max_sum=1.01)
portf.init <- add.constraint(portf.init, type="box", 
 min=0.05, max=0.4)
portf.init <- add.objective(portf.init, type="return", 
 name="mean", multiplier=0)

portf.minES <- add.objective(portf.init, type="risk", name="ES")
portf.minES.RB <- add.objective(portf.minES, type="risk_budget", 
 name="ES", max_prisk=0.3)
portf.minES.RB$constraints[[2]]$max <- rep(1,ncol(R))
portf.minES.EqRB <- add.objective(portf.minES, type="risk_budget", 
 name="ES", min_concentration=TRUE)
portf.minES.EqRB <- add.constraint(portf.minES.EqRB, type="box", 
 min=0.05, max=1, indexnum=2)

portf <- combine.portfolios(list(minES=portf.minES, 
 minES.RB=portf.minES.RB, 
 minES.EqRB=portf.minES.EqRB))
opt.minES <- optimize.portfolio(R, portf, optimize_method="DEoptim", 
 search_size=5000, trace=TRUE, traceDE=0)
- but there is the below error:
  Error in optimize.portfolio(R, portf, optimize_method = "DEoptim", search_size = 5000,  : 
  unused arguments (optimize_method = "DEoptim", search_size = 5000, trace = TRUE, traceDE = 0)
- so i check the portf:

print(portf)

Portfolio 1

---

PortfolioAnalytics Portfolio Specification 

---

Call:
portfolio.spec(assets = funds)

Number of assets: 6 
Asset Names
[1] "CA"   "EMN"  "FIA"  "CTAG" "EM"   "GM"  

Constraints
Enabled constraint types
        - weight_sum 
        - box 

Objectives:
Enabled objective names
        - mean 
        - ES 

Portfolio 2

---

PortfolioAnalytics Portfolio Specification 

---

Call:
portfolio.spec(assets = funds)

Number of assets: 6 
Asset Names
[1] "CA"   "EMN"  "FIA"  "CTAG" "EM"   "GM"  

Constraints
Enabled constraint types
        - weight_sum 
        - box 

Objectives:
Enabled objective names
        - mean 
        - ES 
        - ES 

Portfolio 3

---

PortfolioAnalytics Portfolio Specification 

---

Call:
portfolio.spec(assets = funds)

Number of assets: 6 
Asset Names
[1] "CA"   "EMN"  "FIA"  "CTAG" "EM"   "GM"  

Constraints
Enabled constraint types
        - weight_sum 
        - box 

Objectives:
Enabled objective names
        - mean 
        - ES 
        - ES 
- there shows below warings:

Warning message:
In is.na(le) : is.na() applied to non-(list or vector) of type 'NULL'

**Comment by rossb34** [comment]
the warning you are seeing is a side effect of the ROI packages and can be ignored. I haven't been able to trace exactly where these warnings are coming from in the ROI.\* packages.

**Comment by fengfengyuyu** [comment]
but even  i ignore this waring, the function optimize.portfolio() couldn't be excuted, is there any available way to overcome the problem.

**Comment by rossb34** [comment]
Do you have the DEoptim package installed and loaded? You are specifying DEoptim as your optimization method, but I don't see a `library(DEoptim)` in the code snippet you provided.

**Comment by fengfengyuyu** [comment]
i have installed DEoptim package, call library(DEoptim), but it doesn't work.

**Comment by rossb34** [comment]
Please expand on "it doesn't work". Do you still get the same error or something different?
